### ISSUE TITLE
error: variable log set but not used

### ISSUE THREAD

**Issue by raghebb** [qudreams/nginx-http-radius-module#4]
tried to compile with nginx-1.13.1
and i am getting this error:
src/nginx-http-radius-module/ngx_http_auth_radius.c: In function "ngx_http_auth_radius_create_request":
src/nginx-http-radius-module/ngx_http_auth_radius.c:589:13: error: variable "log" set but not used.

and it's pointing to this line on ngx-http_auth_radius.c
ngx_log_t* log = NULL;

any suggestions?

regards,

**Comment by raghebb** [comment]
i added this line at the beginning of ngx_http_auth_radius.c to ignore the warning and it's working just fine.
`#pragma GCC diagnostic ignored "-Wunused-but-set-variable"`
